<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6ad7f9f9a369913eda25dc7bd93d13fa
{
    public static $prefixLengthsPsr4 = array (
        'Y' => 
        array (
            'Ytic\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ytic\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6ad7f9f9a369913eda25dc7bd93d13fa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6ad7f9f9a369913eda25dc7bd93d13fa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6ad7f9f9a369913eda25dc7bd93d13fa::$classMap;

        }, null, ClassLoader::class);
    }
}
